require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Literar_App' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'

  target 'Literar_AppTests' do
    permissions_path = '../node_modules/react-native-permissions/ios'

    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Literar_App-tvOS' do
  permissions_path = '../node_modules/react-native-permissions/ios'

  # Pods for Literar_App-tvOS

  target 'Literar_App-tvOSTests' do  permissions_path = '../node_modules/react-native-permissions/ios'

    inherit! :search_paths
    # Pods for testing
  end
end
